steps:
# Build the container image
- name: 'gcr.io/cloud-builders/docker'
  args: ['build', '-t', 'gcr.io/tweetqa-338418/api', '.']
# Push the container image to Container Registry
- name: 'gcr.io/cloud-builders/docker'
  args: ['push', 'gcr.io/tweetqa-338418/api']
# Deploy container image to Cloud Run
- name: 'gcr.io/google.com/cloudsdktool/cloud-sdk'
  entrypoint: gcloud
  args: ['run', 'deploy', 'tweetqa-api', '--image', 'gcr.io/tweetqa-338418/api', '--region', 'us-central1', '--timeout', '30']
images:
- gcr.io/tweetqa-338418/api