swagger: "2.0"
info:
  description: This is the swagger file that goes configures the TweetQA API
  version: "1.0.0"
  title: TweetQA API
consumes:
  - "application/json"
produces:
  - "application/json"

basePath: "/"

# Paths supported by the server application
paths:
  /:
    get:
      operationId: "controllers.v1.root.read"
      tags:
        - "Root"
      summary: "Application root to check if things are running correctly"
      description: "Read a status check message"
      responses:
        200:
          description: "TweetQA API successfully read"
          schema:
            type: "string"
  /controllers/v1/QAModelController/read_qa_model/{model_uuid}:
    get:
      operationId: "controllers.v1.QAModelController.read_qa_model"
      tags: 
        - "QAModelController"
      summary: "Application controller to handle QAModel request/response"
      description: "Request a model DTO by uuid"
      parameters:
      - name: model_uuid
        in: path
        required: true
        type: string
        format: path
      responses:
        200:
          description: "Model uuid succesfully found"
          schema:
            type: "array"
            items:
              properties:
                model_uuid: 
                  type: "string"
                created: 
                  type: "string"
                ml_type: 
                  type: "string"
                ml_version:
                  type: "string"
                bleu_score:
                  type: "number"
                rouge_score:
                  type: "number"
                meteor_score:
                  type: "number"
